// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getLink = `-- name: GetLink :one
SELECT url
FROM links
WHERE code = $1
`

func (q *Queries) GetLink(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRow(ctx, getLink, code)
	var url string
	err := row.Scan(&url)
	return url, err
}

const getStats = `-- name: GetStats :one
SELECT url,
  clicks
FROM links
WHERE code = $1
`

type GetStatsRow struct {
	Url    string
	Clicks int32
}

func (q *Queries) GetStats(ctx context.Context, code string) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, getStats, code)
	var i GetStatsRow
	err := row.Scan(&i.Url, &i.Clicks)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE links
SET clicks = clicks + 1
WHERE code = $1
`

func (q *Queries) IncrementClicks(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, incrementClicks, code)
	return err
}

const saveLink = `-- name: SaveLink :exec
INSERT INTO links (code, url)
VALUES ($1, $2)
`

type SaveLinkParams struct {
	Code string
	Url  string
}

func (q *Queries) SaveLink(ctx context.Context, arg SaveLinkParams) error {
	_, err := q.db.Exec(ctx, saveLink, arg.Code, arg.Url)
	return err
}
